/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LikedRouteImport } from './routes/liked'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as ChannelHandleRouteImport } from './routes/channel.$handle'
import { Route as EmbedIdRouteImport } from './routes/embed.$id'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedRoute = LikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelHandleRoute = ChannelHandleRouteImport.update({
  id: '/channel/$handle',
  path: '/channel/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedIdRoute = EmbedIdRouteImport.update({
  id: '/embed/$id',
  path: '/embed/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/results': typeof ResultsRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/embed/$id': typeof EmbedIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/results': typeof ResultsRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/embed/$id': typeof EmbedIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/liked': typeof LikedRoute
  '/results': typeof ResultsRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/embed/$id': typeof EmbedIdRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/channels'
    | '/history'
    | '/liked'
    | '/results'
    | '/shorts'
    | '/studio'
    | '/subscriptions'
    | '/channel/$handle'
    | '/embed/$id'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/channels'
    | '/history'
    | '/liked'
    | '/results'
    | '/shorts'
    | '/studio'
    | '/subscriptions'
    | '/channel/$handle'
    | '/embed/$id'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/channels'
    | '/history'
    | '/liked'
    | '/results'
    | '/shorts'
    | '/studio'
    | '/subscriptions'
    | '/channel/$handle'
    | '/embed/$id'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChannelsRoute: typeof ChannelsRoute
  HistoryRoute: typeof HistoryRoute
  LikedRoute: typeof LikedRoute
  ResultsRoute: typeof ResultsRoute
  ShortsRoute: typeof ShortsRoute
  StudioRoute: typeof StudioRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ChannelHandleRoute: typeof ChannelHandleRoute
  EmbedIdRoute: typeof EmbedIdRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked': {
      id: '/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof LikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$handle': {
      id: '/channel/$handle'
      path: '/channel/$handle'
      fullPath: '/channel/$handle'
      preLoaderRoute: typeof ChannelHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$id': {
      id: '/embed/$id'
      path: '/embed/$id'
      fullPath: '/embed/$id'
      preLoaderRoute: typeof EmbedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChannelsRoute: ChannelsRoute,
  HistoryRoute: HistoryRoute,
  LikedRoute: LikedRoute,
  ResultsRoute: ResultsRoute,
  ShortsRoute: ShortsRoute,
  StudioRoute: StudioRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ChannelHandleRoute: ChannelHandleRoute,
  EmbedIdRoute: EmbedIdRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
